
package javaassignmentgui;

import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Payment extends javax.swing.JFrame {
    public static Car carChosen = null;
    /**
     * Creates new form CarDetails
     */
    public Payment() throws ParseException {
        initComponents();
        String path = null;
        
        
        nameField.setText(Renty.loginUser.getUsername());
        phoneNumField.setText(String.valueOf(Renty.loginUser.getPhoneNum()));
        emailField.setText(Renty.loginUser.getEmail());
        
        carTxt.setText(BookingPay.bookingChosen.getCar());
        plateTxt.setText(BookingPay.bookingChosen.getCarPlate());
        
        carPlateField.setText(BookingPay.bookingChosen.getCarPlate());
        carField.setText(BookingPay.bookingChosen.getCar());
        
        pickupDateField.setText(BookingPay.bookingChosen.getPickupDate());
        returnDateField.setText(BookingPay.bookingChosen.getReturnDate());
        
        date.setText(Renty.toDate());
        
        dayField.setText(String.valueOf(BookingPay.bookingChosen.getDays()));
        totalField.setText(BookingPay.bookingChosen.getTotal());
        
        Car chosenCar = DataIO.chosenCar(plateTxt.getText());
                
        Payment.carChosen = chosenCar;
        
        String type = Payment.carChosen.getType();
        
        if(type.equals("SUV")) {
            path = "src/resource/suv-car.png";
            
        } else if(type.equals("Sedan")) {
            path = "src/resource/sedan.png";
            
        } else if(type.equals("Hatchback")) {
            path = "src/resource/hatchback.png";
            
        } else {
            path = "src/resource/racing-car.png";
        }
        
        
        File resourcesDirectory = new File(path);
        typeImg.setIcon(new ImageIcon(resourcesDirectory.getAbsolutePath()));
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        paymentMethod = new javax.swing.ButtonGroup();
        topBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        carTxt = new javax.swing.JLabel();
        plateTxt = new javax.swing.JLabel();
        confirmBookingBtn = new javax.swing.JButton();
        typeImg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pickupTxt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        returnTxt = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ppRadio = new javax.swing.JRadioButton();
        visaRadio = new javax.swing.JRadioButton();
        tngRadio = new javax.swing.JRadioButton();
        paymentTxt = new javax.swing.JLabel();
        paymentField = new javax.swing.JTextField();
        bookBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nameField = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        phoneNumField = new javax.swing.JLabel();
        carPlateField = new javax.swing.JLabel();
        pickupDateField = new javax.swing.JLabel();
        returnDateField = new javax.swing.JLabel();
        dayField = new javax.swing.JLabel();
        carField = new javax.swing.JLabel();
        totalField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1310, 700));
        setPreferredSize(new java.awt.Dimension(1310, 700));
        getContentPane().setLayout(null);

        topBar.setBackground(new java.awt.Color(0, 0, 0));
        topBar.setMinimumSize(new java.awt.Dimension(1300, 60));
        topBar.setPreferredSize(new java.awt.Dimension(1300, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rent_smalllogo.png"))); // NOI18N

        date.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Payment");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Rent Car");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel18.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Main Menu");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/exit.png"))); // NOI18N
        exitIcon.setToolTipText("Exit");
        exitIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 617, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(exitIcon)
                .addGap(31, 31, 31))
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                                .addComponent(exitIcon)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(topBarLayout.createSequentialGroup()
                                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(topBarLayout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel13))
                                        .addComponent(jLabel12)))
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );

        getContentPane().add(topBar);
        topBar.setBounds(0, 0, 1300, 60);

        jPanel2.setLayout(null);

        carTxt.setFont(new java.awt.Font("Perpetua", 0, 40)); // NOI18N
        carTxt.setText("Lamborghini Urus");
        jPanel2.add(carTxt);
        carTxt.setBounds(50, 140, 340, 39);

        plateTxt.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        plateTxt.setText("JUN 9991");
        jPanel2.add(plateTxt);
        plateTxt.setBounds(50, 190, 117, 28);

        confirmBookingBtn.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        confirmBookingBtn.setText("Confirm Address");
        confirmBookingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingBtnActionPerformed(evt);
            }
        });
        jPanel2.add(confirmBookingBtn);
        confirmBookingBtn.setBounds(290, 530, 177, 40);

        typeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/suv-car.png"))); // NOI18N
        jPanel2.add(typeImg);
        typeImg.setBounds(50, 10, 130, 120);

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel3.setText("Pickup Address:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 220, 120, 30);

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel11.setText("Return Address:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 370, 110, 30);

        pickupTxt.setColumns(20);
        pickupTxt.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        pickupTxt.setRows(5);
        jScrollPane2.setViewportView(pickupTxt);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(180, 220, 290, 140);

        returnTxt.setColumns(20);
        returnTxt.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        returnTxt.setRows(5);
        jScrollPane3.setViewportView(returnTxt);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(180, 380, 290, 140);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(570, 20, 10, 540);

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel4.setText("Booking Summary");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(600, 10, 260, 42);

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel5.setText("Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(600, 70, 80, 21);

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel6.setText("Contact:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(840, 70, 100, 21);

        jLabel7.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(600, 120, 80, 21);

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel8.setText("Car Plate:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(600, 190, 90, 21);

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel9.setText("Car:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(840, 190, 100, 21);

        jLabel14.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel14.setText("Pickup Date:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(600, 240, 110, 21);

        jLabel15.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel15.setText("Return Date:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(840, 240, 110, 21);

        jLabel16.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel16.setText("Days:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(600, 290, 80, 21);

        jLabel17.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel17.setText("Total:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(600, 360, 100, 42);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(590, 350, 487, 10);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(600, 160, 487, 10);

        paymentMethod.add(ppRadio);
        ppRadio.setEnabled(false);
        ppRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ppRadioMousePressed(evt);
            }
        });
        jPanel2.add(ppRadio);
        ppRadio.setBounds(600, 440, 20, 18);

        paymentMethod.add(visaRadio);
        visaRadio.setEnabled(false);
        visaRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visaRadioMousePressed(evt);
            }
        });
        jPanel2.add(visaRadio);
        visaRadio.setBounds(720, 440, 18, 18);

        paymentMethod.add(tngRadio);
        tngRadio.setEnabled(false);
        tngRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tngRadioMousePressed(evt);
            }
        });
        jPanel2.add(tngRadio);
        tngRadio.setBounds(840, 440, 18, 18);

        paymentTxt.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        paymentTxt.setText("Credit Card Number:");
        jPanel2.add(paymentTxt);
        paymentTxt.setBounds(600, 530, 140, 21);

        paymentField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        paymentField.setEnabled(false);
        paymentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentFieldActionPerformed(evt);
            }
        });
        jPanel2.add(paymentField);
        paymentField.setBounds(750, 520, 180, 40);

        bookBtn.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        bookBtn.setText("Book");
        bookBtn.setEnabled(false);
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });
        jPanel2.add(bookBtn);
        bookBtn.setBounds(940, 520, 160, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/paypal.png"))); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(630, 420, 70, 60);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/visa.png"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(750, 420, 70, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/touchngo.png"))); // NOI18N
        jPanel2.add(jLabel21);
        jLabel21.setBounds(860, 420, 70, 53);

        nameField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        nameField.setText("name");
        jPanel2.add(nameField);
        nameField.setBounds(670, 70, 150, 20);

        emailField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        emailField.setText("email");
        jPanel2.add(emailField);
        emailField.setBounds(670, 120, 150, 21);

        phoneNumField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        phoneNumField.setText("contact number");
        jPanel2.add(phoneNumField);
        phoneNumField.setBounds(950, 70, 110, 20);

        carPlateField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        carPlateField.setText("car plate");
        jPanel2.add(carPlateField);
        carPlateField.setBounds(710, 190, 90, 20);

        pickupDateField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        pickupDateField.setText("pickupDate");
        jPanel2.add(pickupDateField);
        pickupDateField.setBounds(710, 240, 100, 21);

        returnDateField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        returnDateField.setText("returnDate");
        jPanel2.add(returnDateField);
        returnDateField.setBounds(950, 240, 110, 21);

        dayField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        dayField.setText("day");
        jPanel2.add(dayField);
        dayField.setBounds(710, 290, 80, 21);

        carField.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        carField.setText("car");
        jPanel2.add(carField);
        carField.setBounds(950, 190, 120, 21);

        totalField.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        totalField.setText("total");
        jPanel2.add(totalField);
        totalField.setBounds(690, 360, 240, 42);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(80, 70, 1120, 580);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/car.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, -4, 1310, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseClicked
//       this.setVisible(false);
//        
//        MainMenu mm = new MainMenu();
//        mm.setVisible(true);
    }//GEN-LAST:event_dateMouseClicked

    private void paymentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentFieldActionPerformed

    private void confirmBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingBtnActionPerformed
        String pickupAdd = pickupTxt.getText();
        String returnAdd = returnTxt.getText();
        
        if(!pickupAdd.equals("") && !returnAdd.equals("")) {
            ppRadio.setEnabled(true);
            visaRadio.setEnabled(true);
            tngRadio.setEnabled(true);
            paymentField.setEnabled(true);
            bookBtn.setEnabled(true);
            
//            pickupAddField.setText(pickupAdd);
//            returnAddField.setText(returnAdd);
            
            pickupTxt.setEnabled(false);
            returnTxt.setEnabled(false);
            confirmBookingBtn.setEnabled(false);
         
        } else {
            JOptionPane.showMessageDialog(null, "Please Input Valid Address.", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmBookingBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        String paymentInfo = paymentField.getText();
        
        try {
            Integer.parseInt(paymentInfo);
            
            
            String payMethod = null;
            boolean Error = false;
            if(ppRadio.isSelected()){
                payMethod = "PayPal";
            } else if(visaRadio.isSelected()){
                payMethod = "Credit Card";
            } else if(tngRadio.isSelected()) {
                payMethod = "TnG";
            } else {
                Error = true;
            }
            
            if(!Error) {
                
                BookingPay.bookingChosen.setPickupAdd(pickupTxt.getText().replace("\n", " "));
                BookingPay.bookingChosen.setReturnAdd(returnTxt.getText().replace("\n", " "));
                BookingPay.bookingChosen.setPaymentMethod(payMethod);
                BookingPay.bookingChosen.setPaymentDetails(paymentInfo);
                BookingPay.bookingChosen.setStatus("Paid");
                
                DataIO.WriteToText();

                JOptionPane.showMessageDialog(null, "Booking Made Successfully. Total Paid: " + totalField.getText()+ ".");

                this.setVisible(false);
                MainMenu mm = new MainMenu();
                mm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please Select Atleast one Payment Method.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }  catch (NumberFormatException e)  
        { 
           JOptionPane.showMessageDialog(null, "Please Input Valid Payment Info.", "Error!", JOptionPane.ERROR_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
       
    }//GEN-LAST:event_bookBtnActionPerformed

    private void ppRadioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppRadioMousePressed
        paymentTxt.setText("");

        paymentTxt.setText("PayPal Number:");
    }//GEN-LAST:event_ppRadioMousePressed

    private void visaRadioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visaRadioMousePressed
        paymentTxt.setText("");

        paymentTxt.setText("Credit Card Number:");
    }//GEN-LAST:event_visaRadioMousePressed

    private void tngRadioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tngRadioMousePressed
        paymentTxt.setText("");
        paymentTxt.setText("TnG Number:");
    }//GEN-LAST:event_tngRadioMousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.setVisible(false);
        
        RentCar rent = new RentCar();
        rent.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        this.setVisible(false);
        
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        this.setVisible(false);
        DataIO.logout();
    }//GEN-LAST:event_exitIconMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Payment().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JLabel carField;
    private javax.swing.JLabel carPlateField;
    private javax.swing.JLabel carTxt;
    private javax.swing.JButton confirmBookingBtn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dayField;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel nameField;
    private javax.swing.JTextField paymentField;
    private javax.swing.ButtonGroup paymentMethod;
    private javax.swing.JLabel paymentTxt;
    private javax.swing.JLabel phoneNumField;
    private javax.swing.JLabel pickupDateField;
    private javax.swing.JTextArea pickupTxt;
    private javax.swing.JLabel plateTxt;
    private javax.swing.JRadioButton ppRadio;
    private javax.swing.JLabel returnDateField;
    private javax.swing.JTextArea returnTxt;
    private javax.swing.JRadioButton tngRadio;
    private javax.swing.JPanel topBar;
    private javax.swing.JLabel totalField;
    private javax.swing.JLabel typeImg;
    private javax.swing.JRadioButton visaRadio;
    // End of variables declaration//GEN-END:variables
}
