/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaassignmentgui;

import java.io.FileNotFoundException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;

/**
 *
 * @author bryan
 */
public class AdminManageIndiBooking extends javax.swing.JFrame {
    
    AdminManageBookings amb = new AdminManageBookings();
    
    /**
     * Creates new form AdminManageIndiBooking
     */
    public AdminManageIndiBooking() {
        initComponents();
        setLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        date = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        rentCarBtn = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        daysBookedLabel = new javax.swing.JLabel();
        totalPaymentLabel = new javax.swing.JLabel();
        paymentMethodLabel = new javax.swing.JLabel();
        pickupAddInput = new javax.swing.JTextField();
        returnAddInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewInput = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        daysBookedLabel1 = new javax.swing.JLabel();
        daysBookedLabel2 = new javax.swing.JLabel();
        daysBookedLabel3 = new javax.swing.JLabel();
        daysBookedLabel4 = new javax.swing.JLabel();
        daysBookedLabel5 = new javax.swing.JLabel();
        daysBookedLabel6 = new javax.swing.JLabel();
        daysBookedLabel7 = new javax.swing.JLabel();
        daysBookedLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bookingIdLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        topBar.setBackground(new java.awt.Color(0, 0, 0));
        topBar.setMinimumSize(new java.awt.Dimension(1300, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rent_smalllogo.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Main Menu");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Car Details");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        date.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateMouseClicked(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/exit.png"))); // NOI18N
        exitIcon.setToolTipText("Exit");
        exitIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });

        rentCarBtn.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        rentCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        rentCarBtn.setText("Rent Car");
        rentCarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rentCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentCarBtnMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentCarBtn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 590, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitIcon)
                .addGap(36, 36, 36))
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitIcon)
                    .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(date)
                        .addComponent(rentCarBtn)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(topBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        getContentPane().add(topBar);
        topBar.setBounds(0, 0, 1300, 60);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel4.setText("Contact :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(820, 50, 110, 30);

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 110, 30);

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 50, 110, 30);

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel6.setText("Car :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 150, 110, 30);

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel7.setText("Car Plate:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 200, 110, 30);

        jLabel8.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel8.setText("Booking Date:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 310, 143, 30);

        jLabel9.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel9.setText("Pickup Address:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 150, 143, 30);

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel12.setText("Return Address:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 200, 143, 30);

        jLabel13.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel13.setText("Pickup Date:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 360, 143, 30);

        jLabel14.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel14.setText("Return Date:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 410, 143, 30);

        jLabel15.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel15.setText("Days Booked:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 310, 121, 28);

        jLabel16.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel16.setText("Total Payment:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(460, 360, 135, 30);

        jLabel17.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel17.setText("Payment Method:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(460, 410, 168, 30);

        jLabel18.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel18.setText("Review:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(830, 310, 73, 28);

        jLabel19.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel19.setText("Customer Information");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(28, 11, 195, 30);

        jLabel20.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel20.setText("Car Information");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(30, 110, 140, 30);

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel21.setText("Booking Information");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 270, 180, 30);

        daysBookedLabel.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jPanel1.add(daysBookedLabel);
        daysBookedLabel.setBounds(640, 390, 160, 0);

        totalPaymentLabel.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jPanel1.add(totalPaymentLabel);
        totalPaymentLabel.setBounds(640, 440, 160, 0);

        paymentMethodLabel.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jPanel1.add(paymentMethodLabel);
        paymentMethodLabel.setBounds(640, 490, 160, 0);

        pickupAddInput.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jPanel1.add(pickupAddInput);
        pickupAddInput.setBounds(620, 140, 610, 40);

        returnAddInput.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        returnAddInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnAddInputActionPerformed(evt);
            }
        });
        jPanel1.add(returnAddInput);
        returnAddInput.setBounds(620, 190, 610, 40);

        reviewInput.setColumns(20);
        reviewInput.setRows(5);
        jScrollPane1.setViewportView(reviewInput);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(930, 310, 300, 110);

        jButton2.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jButton2.setText("Modify");
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 520, 110, 30);

        daysBookedLabel1.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel1.setText("value");
        jPanel1.add(daysBookedLabel1);
        daysBookedLabel1.setBounds(170, 410, 180, 30);

        daysBookedLabel2.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel2.setText("value");
        jPanel1.add(daysBookedLabel2);
        daysBookedLabel2.setBounds(170, 50, 200, 30);

        daysBookedLabel3.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel3.setText("value");
        jPanel1.add(daysBookedLabel3);
        daysBookedLabel3.setBounds(620, 50, 180, 30);

        daysBookedLabel4.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel4.setText("value");
        jPanel1.add(daysBookedLabel4);
        daysBookedLabel4.setBounds(930, 50, 180, 30);

        daysBookedLabel5.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel5.setText("value");
        jPanel1.add(daysBookedLabel5);
        daysBookedLabel5.setBounds(170, 150, 180, 30);

        daysBookedLabel6.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel6.setText("value");
        jPanel1.add(daysBookedLabel6);
        daysBookedLabel6.setBounds(170, 200, 180, 30);

        daysBookedLabel7.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel7.setText("value");
        jPanel1.add(daysBookedLabel7);
        daysBookedLabel7.setBounds(170, 310, 180, 30);

        daysBookedLabel8.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        daysBookedLabel8.setText("value");
        jPanel1.add(daysBookedLabel8);
        daysBookedLabel8.setBounds(170, 360, 180, 40);

        jButton3.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jButton3.setText("Modify");
        jPanel1.add(jButton3);
        jButton3.setBounds(570, 530, 110, 30);

        jButton4.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jButton4.setText("Approve");
        jPanel1.add(jButton4);
        jButton4.setBounds(440, 520, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 110, 1260, 570);

        jLabel1.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel1.setText("Booking ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 70, 110, 30);

        bookingIdLabel.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        bookingIdLabel.setText("booking_id");
        getContentPane().add(bookingIdLabel);
        bookingIdLabel.setBounds(640, 70, 160, 30);

        backBtn.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(40, 70, 110, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/renty_logo.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1300, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setVisible(false);

        MainMenu mm = new MainMenu();
        mm.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateMouseClicked

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked

        try {
            DataIO.WriteToText();
            System.exit(0);
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageIndiBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitIconMouseClicked

    private void rentCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentCarBtnMouseClicked
        this.setVisible(false);

        RentCar rent = new RentCar();
        rent.setVisible(true);
    }//GEN-LAST:event_rentCarBtnMouseClicked

    private void returnAddInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnAddInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnAddInputActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        AdminManageBookings amb = new AdminManageBookings();
        amb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageIndiBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageIndiBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageIndiBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageIndiBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManageIndiBooking().setVisible(true);
            }
        });
    }
    
    public void setLabels() {
        // getting values from previous selected booking
        bookingIdLabel.setText(amb.chosenBooking.getBookingID());
        
        // Pre fill values (user details)
        nameInput.setText(amb.chosenBooking.getName());
        emailInput.setText(amb.chosenBooking.getEmail());
        contactInput.setText(amb.chosenBooking.getContact());
        
        // Pre fill values (car information)
        carInput.setText(amb.chosenBooking.getCar());
        carPlateInput.setText(amb.chosenBooking.getCarPlate());
        pickupAddInput.setText(amb.chosenBooking.getPickupAdd());
        returnAddInput.setText(amb.chosenBooking.getReturnAdd());
        
        // Pre fill values (booking details)
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bookingIdLabel;
    private javax.swing.JLabel date;
    private javax.swing.JLabel daysBookedLabel;
    private javax.swing.JLabel daysBookedLabel1;
    private javax.swing.JLabel daysBookedLabel2;
    private javax.swing.JLabel daysBookedLabel3;
    private javax.swing.JLabel daysBookedLabel4;
    private javax.swing.JLabel daysBookedLabel5;
    private javax.swing.JLabel daysBookedLabel6;
    private javax.swing.JLabel daysBookedLabel7;
    private javax.swing.JLabel daysBookedLabel8;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JTextField pickupAddInput;
    private javax.swing.JLabel rentCarBtn;
    private javax.swing.JTextField returnAddInput;
    private javax.swing.JTextArea reviewInput;
    private javax.swing.JPanel topBar;
    private javax.swing.JLabel totalPaymentLabel;
    // End of variables declaration//GEN-END:variables
}
